### ISSUE TITLE
How I create a basket for a Minecraft server?

### ISSUE THREAD

**Issue by iSnakeBuzz** [grp-gg/tebex_headless#3]
Hello,

I have come across the Tebex API in the official documentation, and while exploring its functionalities, I encountered an issue. Specifically, I am unable to create a basket for a Minecraft Server.

As per Tebex documentation, it's mentioned that the username of the user needs to be sent in the create basket POST request. However, I couldn't find this option in the API, or it's not apparent to me.

Could you please provide guidance on how to create a Minecraft Basket using this API?

Thanks.

**Comment by Tynopia** [comment]
Hi @iSnakeBuzz,

First of all, thanks for your issue and [pull request](https://github.com/grp-gg/tebex_headless/pull/4), and sorry for this late answer.

I've added a [CreateMinecraftBasket](https://github.com/grp-gg/tebex_headless/blob/main/index.ts#L545-L569) function, which has the `username` attribute, but follows the same logic as the [CreateBasket](https://github.com/grp-gg/tebex_headless/blob/main/index.ts#L521-L543) function. In your pull request, I saw that you added the `username` attribute directly in the `CreateBasket` logic, which can cause confusion for other developers when they use the API because there is no username required in other games (like FiveM, which requires logging in with your cfx.re account).

I also noticed that you added a "both" value to the [PackageType](https://github.com/grp-gg/tebex_headless/blob/main/index.ts#L310-L317) type, but I can't find any reference in the official headless API documentation. Can you send me a link so that I can implement it if it exists?

You can now use [Version 1.6.0](https://www.npmjs.com/package/tebex_headless) to access the newest updates. I also fixed the Apply and Remove functions and added Jest integration tests, as you can see [here](https://github.com/grp-gg/tebex_headless/tree/main/tests).

**Comment by iSnakeBuzz** [comment]
About the PackageType 'both,' it's because if you set a package that can be a subscription and a one-time purchase, the API, when you retrieve your packages, sets the type to 'both' instead of 'subscription' or 'single.

**Comment by Tynopia** [comment]
Unfortunately, the documentation for the headless API is already outdated, and I find myself having to reach out to the Overwolf developer once again. Could you kindly share a cURL request for your package? This way, I can examine the package type.

**Comment by iSnakeBuzz** [comment]
Sure, here you have the curl:

```shell
curl --request GET \
  --url https://headless.tebex.io/api/accounts/t408-c3782e160439032a45c54c2526bbea642d083d3e/packages/5979129 \
  --header 'User-Agent: insomnia/2023.5.8' 
```

**Comment by Tynopia** [comment]
Yeah, I can see it and have added the 'both' value to the PackageType! You can now use [Version 1.6.1](https://www.npmjs.com/package/tebex_headless).
